/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package biblioteca.views;

import biblioteca.models.Biblioteca;
import biblioteca.models.Libro;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Modelo que representa la ventana de BuscarLibro
 * @author Camila
 * @since 20250312
 * @version 1.0
 */
public class BuscarLibro extends javax.swing.JDialog {
    //Atributos 
    /**
    * Instancia de Biblioteca
    */
    private Biblioteca biblioteca;
    /**
    * Instancia de VentanaPrincipal
    */
    private VentanaPrincipal ventana;
    
    /**
     * Inicializa los atributos de la clase BuscarLibro
     *
     * @param     parent
     * @param     modal
     * @param     biblioteca
     * @param     ventana
    */
    public BuscarLibro(java.awt.Frame parent, boolean modal, Biblioteca biblioteca, VentanaPrincipal ventana) {
        super(parent, modal);
        initComponents();
        this.biblioteca = biblioteca;
        this.ventana = ventana;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelTitulo1 = new javax.swing.JPanel();
        textoBuscarLibro = new javax.swing.JLabel();
        iconoBuscarLibro = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        txtLibro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textoPreguntarIdLibroBuscar = new javax.swing.JLabel();
        txtIdLibroBuscar = new javax.swing.JTextField();
        btnBuscarLibro = new javax.swing.JPanel();
        txtBusc = new javax.swing.JLabel();
        iconoBusc = new javax.swing.JLabel();
        textBuscar1 = new javax.swing.JLabel();
        txtIdLibro = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JLabel();
        iconoLibro = new javax.swing.JLabel();
        iconoLibro2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        panelTitulo1.setBackground(new java.awt.Color(193, 138, 255));

        textoBuscarLibro.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        textoBuscarLibro.setForeground(new java.awt.Color(255, 255, 255));
        textoBuscarLibro.setText("Buscar libro");

        iconoBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/images/buscarLibro.png"))); // NOI18N

        javax.swing.GroupLayout panelTitulo1Layout = new javax.swing.GroupLayout(panelTitulo1);
        panelTitulo1.setLayout(panelTitulo1Layout);
        panelTitulo1Layout.setHorizontalGroup(
            panelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulo1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textoBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconoBuscarLibro)
                .addGap(48, 48, 48))
        );
        panelTitulo1Layout.setVerticalGroup(
            panelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenido.setBackground(new java.awt.Color(213, 183, 247));

        txtLibro.setFont(new java.awt.Font("Segoe Print", 1, 40)); // NOI18N
        txtLibro.setText("Buscar");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        textoPreguntarIdLibroBuscar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        textoPreguntarIdLibroBuscar.setText("Ingrese el id del libro que desea buscar: ");

        txtIdLibroBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLibroBuscarActionPerformed(evt);
            }
        });

        btnBuscarLibro.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarLibroMouseExited(evt);
            }
        });

        txtBusc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBusc.setText("Buscar libro");

        iconoBusc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/images/completado.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarLibroLayout = new javax.swing.GroupLayout(btnBuscarLibro);
        btnBuscarLibro.setLayout(btnBuscarLibroLayout);
        btnBuscarLibroLayout.setHorizontalGroup(
            btnBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusc)
                .addGap(18, 18, 18)
                .addComponent(iconoBusc)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btnBuscarLibroLayout.setVerticalGroup(
            btnBuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLibroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconoBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(btnBuscarLibroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtBusc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textoPreguntarIdLibroBuscar)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPreguntarIdLibroBuscar)
                    .addComponent(txtIdLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        textBuscar1.setFont(new java.awt.Font("Segoe Print", 1, 40)); // NOI18N
        textBuscar1.setText("Buscar");

        txtIdLibro.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtIdLibro.setText(".");

        txtTituloLibro.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtTituloLibro.setText(".");

        iconoLibro.setText(".");

        iconoLibro2.setText(".");

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtLibro))
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconoLibro)
                            .addComponent(iconoLibro2))
                        .addGap(18, 18, 18)
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloLibro)
                            .addComponent(txtIdLibro))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenidoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(textBuscar1)
                    .addContainerGap(382, Short.MAX_VALUE)))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdLibro)
                    .addComponent(iconoLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloLibro)
                    .addComponent(iconoLibro2))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenidoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(textBuscar1)
                    .addContainerGap(289, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del boton buscarLibro al hacer click
     * @param     evt
    */
    private void btnBuscarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarLibroMouseClicked
        try{
            long idLibro = Long.parseLong(this.txtIdLibroBuscar.getText());
            Libro libroEncontrado = this.biblioteca.buscarLibro(idLibro);
            if (libroEncontrado == null){
                JOptionPane.showMessageDialog(this, "No se encontro el libro");
                this.dispose();
            }
            else{
                this.txtLibro.setText ("Libro encontrado");
                this.txtIdLibro.setText ("Id libro " + libroEncontrado.getId());
                this.txtTituloLibro.setText ("Titulo libro " + libroEncontrado.getTitulo());
                ImageIcon icono = new ImageIcon(getClass().getResource("/biblioteca/images/libro.png"));
                this.iconoLibro.setIcon (icono);
                this.iconoLibro2.setIcon (icono);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un numero");
            this.txtIdLibroBuscar.setText("");
        }
    }//GEN-LAST:event_btnBuscarLibroMouseClicked

    private void btnBuscarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarLibroMouseEntered

    }//GEN-LAST:event_btnBuscarLibroMouseEntered

    private void btnBuscarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarLibroMouseExited

    }//GEN-LAST:event_btnBuscarLibroMouseExited

    private void txtIdLibroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLibroBuscarActionPerformed
        
    }//GEN-LAST:event_txtIdLibroBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscarLibro;
    private javax.swing.JLabel iconoBusc;
    private javax.swing.JLabel iconoBuscarLibro;
    private javax.swing.JLabel iconoLibro;
    private javax.swing.JLabel iconoLibro2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTitulo1;
    private javax.swing.JLabel textBuscar1;
    private javax.swing.JLabel textoBuscarLibro;
    private javax.swing.JLabel textoPreguntarIdLibroBuscar;
    private javax.swing.JLabel txtBusc;
    private javax.swing.JLabel txtIdLibro;
    private javax.swing.JTextField txtIdLibroBuscar;
    private javax.swing.JLabel txtLibro;
    private javax.swing.JLabel txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
